version: 2

builds:
  - main: ./cmd/plcbundle
    binary: plcbundle
    env:
      - CGO_ENABLED=1
    goos: [linux]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - formats: ["tar.gz"]

release:
  disable: true
