# Build workflow - test compilation on pull requests

when:
  - event: ["push", "pull_request"]
    branch: ["main", "develop"]

engine: "nixery"

dependencies:
  nixpkgs:
    - go
    - gcc
    - git
    - zstd
    - zstd.dev

environment:
  CGO_ENABLED: "1"
  GOPATH: "/workspace/go"

steps:
  - name: "Download dependencies"
    command: |
      go mod download
      go mod verify

  - name: "Run tests"
    command: |
      go test -v ./...

  - name: "Build binary"
    command: |
      go build -o plcbundle ./cmd/plcbundle
      ./plcbundle version
      echo "✓ Build successful"
